### PR TITLE
Add wrap button

### PR DESCRIPTION
**Pull request by cybertelx**
This will make it easier for people to wrap their sSB into wsSB.

This adds a new menu button "Wrap" on the drawer and adds a wrap page.

### CODE REVIEW

**Comment by cybertelx** [comment]
Note: Currently, the Wrap icon borrows the Borrow icon (no pun intended), UX team please come up with a cool icon! Thanks

**Comment by cybertelx** [comment]
@0xOtoguro

**Comment by 0x9nikopol** [comment]
@cybertelx Will add this right after the redeem page is added. Thank you ser!

**Comment by cybertelx** [comment]
(note: for people who are using this preview dev version, note that "RFV" shows 147$ because the assets are outside of the treasury and instead in another contract. the main site uses a hardcoded value instead, cuz redistribution.)

**Comment by cybertelx** [comment]
fixed conflicts

**Comment by cybertelx** [comment]
oh no i broke it

**Review by 0xOtoguro — APPROVED** [review]

**Pull request merged**
